### ISSUE TITLE
Transmission Openvpn PIA - Error: portTested: http error 0: No Response

### ISSUE THREAD

**Issue by mwarf** [joskore/media-docker#108]
**Describe the bug**
When using PIA (Private Internet Access) and / Transmission OpenVPN containers - torrents cannot connect to peers. 

**To Reproduce**
1. Choose Torrenting option (Transmission)
2. Launch transmission and transmission_proxy containers
3. check logs for errors
4. Note Error: portTested: http error 0: No Response when transmission seeks an open port.

**Expected behavior**
Transmission connects through Traefik reverse proxy to the outside world, downloads happen, in reality transmission just hangs.

I solved this by adding the DNS flags provided in the docker-compose template provided by the transmission / openvpn container:
"  dns:
    - 8.8.8.8
    - 8.8.4.4
"
Once this was added, torrents worked as expected, but it was not provided as default.
Example template: https://github.com/haugene/docker-transmission-openvpn/blob/master/docker-compose.yml

**Comment by kevinwmerritt** [comment]
I'm using `media-docker` as a reference for how to use transmission and traefik with docker compose. I also was not able to ping the internet from inside the container without adding the the `dns` configuration.

**Comment by joskore** [comment]
thanks for finding this! i admittedly stopped using torrents entirely a year or so ago, so i haven’t had direct experience since then. i’m not sure if that’s new behavior, but i certainly don’t recall that being required back then 🙍

i’m traveling and computer usage is limited right now, but if someone would be willing to make that change and a pull request, i’d be glad to review and merge it!

thanks again

**Comment by joskore** [comment]
added in #109, let me know if issues persist or further issues occur, otherwise i'll close this out in a few days

thanks again for letting me know about this issue
