### ISSUE TITLE
add new ${BASE_DIR_CONFIG} and default to '/config' if necessary

### ISSUE THREAD

**Issue by powerdude** [joskore/media-docker#67]
**Is your feature request related to a problem? Please describe.**
I have an existing setup that i want to move over to this, but the current expectation of having a `/config` is a bit jarring.

**Describe the solution you'd like**
it would be nice to be able to choose if you want to use a `/config` on your host.  So instead of this:
 ` - ${BASE_DIR}/calibreweb/config:/config` 
would like to do this: 
 ` - ${BASE_DIR}/calibreweb${CONFIG}:/config` 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by joskore** [comment]
what would be the benefit to not having the service directory segmented as it is presently? is migrating your current config into an additional-level-deep sub-directory prohibitive?

the current intention is that a service could have multiple sub-directories that need to be mapped but serve separate purposes. so, a config directory for containing configs as in the example, but maybe we also include service-level backups or swap space. would you really want those potentially included in the same directory as your config?

just trying to understand the core issue, because the solution you're recommending can't be implemented quite as simply as it's stated above :)

**Comment by powerdude** [comment]
i see what you're saying.  I guess for the scenarios you stated, i'd be more likely to do the following based on what i saw in the previous portainer config:
`/config/portainer/`
`/backup/portainer/`
`/swap/portainer`

this would allow me to have separate volumes and manage my the space the way i want to and, possibly, allow for greater flexibility.

I guess my point is to allow the user to set things up like *they* want to as long as it is not too impactful to you and the product you're providing.  Forcing the user to have a `config` subdirectory seems a bit forceful and unnecessary, especially if the user isn't concerned with or have other separate purposes.  

Almost similar to the media environment variables you introduced.  You're giving the user more control over their environment.

**Comment by joskore** [comment]
there's definitely some ways we can improve directory layout. i don't have an immediate change for you, but improving this experience will be on my list to think about

**Comment by joskore** [comment]
i know that you've already taken a bit of a look at #103, but that's basically the implementation of this discussion. let me know if you see any issues or have any questions before it gets merged and this gets closed :)

**Comment by joskore** [comment]
implemented in #103 

1. a CONTAINER_DIR variable is created in the .env for setting primary container storage
    - new users will have this set to ./media-docker/containers by default
    - existing users will have CONTAINER_DIR set to BASE_DIR on first run after the update
2. a CONTAIN_CONF_SUBDIR variable is created in the .env for setting a subdir to suffix onto specific containers' config volume mappings
    - new and existing users will have this default to /config to preserve existing behavior
3. both vars are configurable by the .env directly or by the directory configuration menu
