### ISSUE TITLE
Add ubuntu version requirement?

### ISSUE THREAD

**Issue by 1DontEx1st** [joskore/media-docker#7]
I'm going to be setting up a server from scratch so I don't think I'll have a problem, but it would be nice to know if there's a minimum spec and/or tested version(s). Thanks!

**Comment by joskore** [comment]
i've added some notes to the README on minimums, recommended, and tested system specs / OS. thanks for the thought!

**Comment by 1DontEx1st** [comment]
Thanks for the package!
I'm curious, and not sure if this should be brought up in an issue - what
is the ideal type of target for this? I have a home server that is behind a
router, so I'm not sure what domain to use. Is the suggested use case an
exposed server?

**Comment by joskore** [comment]
it's applicable in all sorts of environments, but it's built and tested on my personal environment, so it has biases built in from that. for whatever it's worth, my systems are dedicated servers in a co-location environment. i test locally also, but the actual system is all out there.

if you don't have a domain for reverse proxying and are only looking to work off of ports, all of the traefik system is irrelevant. that's really the only thing that needs to change between the two setups.

traefik manages SSL termination and forwarding requests based on hostname rather than exposing ports directly. if you don't / can't use that system, traefik can be removed / disabled, the traefik labels on all of the containers in the docker-compose can be removed, and the relevant ports can be exposed in the docker-compose file. from there, you can port forward in your router if you'd like if you want external access.

hopefully that's helpful!

**Comment by 1DontEx1st** [comment]
that's *extremely *helpful, but I have one more stupid question: how do I
manage docker? I have zero experience using it...is it entirely through the
compose-file or is there a console like there would be in a VM setup?

**Comment by 1DontEx1st** [comment]
Great, that'll be a good enough start to help me transition from the vpc
mindset to container mindset, thanks again!
