### ISSUE TITLE
TOML file doesnt have DNS Challenge added after beeing selected in menu

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#93]
**Describe the bug**
I have set DNS challenge in Traefik Config Menu.  But specific values are missing in resulting TOML file.
  [acme.dnsChallenge]
  provider = "cloudflare"

**To Reproduce**
Setup up Traefik
Choose DNS chalenge
fill in provider info
check resulting TOML

**Expected behavior**
After selecting DNS challenge, TOML file should reflect them

**Comment by joskore** [comment]
yikes, not sure how this slipped by. basically, whiptail menus suck and they're especially problematic when you have circular references or exit calls in child menus. both of these were happening here, and they combined to mean that once you entered the DNS challenge provider's configuration items, the process simply exited rather than allowing them to write to the config file.

resovled in #95

**Comment by joskore** [comment]
feel free to reopen if issues recur :)
